### ISSUE TITLE
nav links not working

### ISSUE THREAD

**Issue by jdgc14** [Caribe-Dev/caribe-page#5]
click on the links and they don't redirect to anything
![image](https://github.com/Caribe-Dev/caribe-page/assets/101612705/b0b727fb-f948-4df3-8019-8829b0b25bfa)

**Comment by makinox** [comment]
Working on it

**Comment by makinox** [comment]
done on https://github.com/Caribe-Dev/caribe-page/tree/d8cd63e309fe9854a04b1e7f4d29a343f182b768
